In [35]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
from pandas_datareader import data as web
import matplotlib.pyplot as plt
import ta
import warnings
import requests
warnings.filterwarnings("ignore")

# Scrape the S&P 500 constituents table from Wikipedia
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
response = requests.get(url, headers=headers)
sp500 = pd.read_html(response.text)[0]

# Standardize ticker symbols and extract a unique list of S&P 500 tickers
sp500['Symbol'] = sp500['Symbol'].str.replace('.', '-')
symbols_list = sp500['Symbol'].unique().tolist()

end_date = '2025-12-15'
start_date = pd.to_datetime(end_date) - pd.DateOffset(365*8)

# Download data
df = yf.download(tickers=symbols_list, start=start_date, end=end_date).stack()
df.index.names = ['date', 'ticker']
df.columns = df.columns.str.lower()

df

[*********************100%***********************]  501 of 501 completed

Price                   close        high         low        open       volume
date       ticker
2017-12-18 A        63.697094   64.497307   63.527636   63.913619    2306300.0
           AAPL     41.316124   41.498793   40.950785   40.955470  117684400.0
           ABBV     69.745369   70.391749   69.290771   69.376005    4768300.0
           ABT      49.003811   49.108073   48.152323   48.239212    6053900.0
           ACGL     28.961201   29.338389   28.923166   29.217944    1212300.0
...                       ...         ...         ...         ...          ...
2025-12-12 XYZ      64.750000   65.120003   62.799999   63.610001    6642300.0
           YUM     151.059998  151.169998  148.570007  148.899994    1894500.0
           ZBH      91.589996   93.160004   90.570000   92.599998    2734200.0
           ZBRA    268.390015  274.269989  265.970001  273.630005     543200.0
           ZTS     118.660004  121.080002  118.209999  119.190002    5071100.0

[982534 rows x 5 columns]

In [36]:
# Calculate Garman-Klass volatility using high, low, open and adjusted close prices
df['garman_klass_vol'] = ((np.log(df['high']) - np.log(df['low']))**2 / 2 - (2 * np.log(2) - 1) * (np.log(df['close']) - np.log(df['open']))**2)

# Calculate rsi on each stock
df['rsi'] = df.groupby(level=1)['close'].transform(lambda x: ta.momentum.rsi(close=x, window=20))

# Calculate Bollinger Bands for all stocks
df['bb_low'] = df.groupby(level=1)['close'].transform(lambda x: ta.volatility.BollingerBands(close=np.log1p(x), window=20).bollinger_lband())

df['bb_mid'] = df.groupby(level=1)['close'].transform(lambda x: ta.volatility.BollingerBands(close=np.log1p(x), window=20).bollinger_mavg())

df['bb_high'] = df.groupby(level=1)['close'].transform(lambda x: ta.volatility.BollingerBands(close=np.log1p(x), window=20).bollinger_hband())

# Compute a z‑score normalized 14‑day ATR(Average True Range) to capture each stock’s relative volatility profile
def compute_atr(stock_data):
    atr_indicator = ta.volatility.AverageTrueRange(
        high=stock_data['high'],
        low=stock_data['low'],
        close=stock_data['close'],
        window=14
    )
    atr = atr_indicator.average_true_range()
    return atr.sub(atr.mean()).div(atr.std())

df['atr'] = df.groupby(level=1, group_keys=False).apply(compute_atr)

# Compute a z‑score normalized MACD(Moving Average Convergence Divergence) signal to capture momentum shifts in each stock’s trend
def compute_macd(close):
    macd_indicator = ta.trend.MACD(close=close, window_slow=26, window_fast=12, window_sign=9)
    macd = macd_indicator.macd()
    return macd.sub(macd.mean()).div(macd.std())

df['macd'] = df.groupby(level=1, group_keys=False)['close'].apply(compute_macd)

# Calculate dollar volume (price × shares traded) to measure liquidity in millions of dollars
df['dollar_volume'] = (df['close']*df['volume']) / 1e6
df

Price                   close        high         low        open  \
date       ticker
2017-12-18 A        63.697094   64.497307   63.527636   63.913619
           AAPL     41.316124   41.498793   40.950785   40.955470
           ABBV     69.745369   70.391749   69.290771   69.376005
           ABT      49.003811   49.108073   48.152323   48.239212
           ACGL     28.961201   29.338389   28.923166   29.217944
...                       ...         ...         ...         ...
2025-12-12 XYZ      64.750000   65.120003   62.799999   63.610001
           YUM     151.059998  151.169998  148.570007  148.899994
           ZBH      91.589996   93.160004   90.570000   92.599998
           ZBRA    268.390015  274.269989  265.970001  273.630005
           ZTS     118.660004  121.080002  118.209999  119.190002

Price                   volume  garman_klass_vol        rsi    bb_low  \
date       ticker
2017-12-18 A         2306300.0          0.000110        NaN       NaN
           AAPL    117684400.0          0.000059        NaN       NaN
           ABBV      4768300.0          0.000113        NaN       NaN
           ABT       6053900.0          0.000098        NaN       NaN
           ACGL      1212300.0          0.000071        NaN       NaN
...                        ...               ...        ...       ...
2025-12-12 XYZ       6642300.0          0.000536  47.124784  4.078423
           YUM       1894500.0          0.000070  55.902246  4.964153
           ZBH       2734200.0          0.000351  43.820179  4.484522
           ZBRA       543200.0          0.000328  51.744682  5.418711
           ZTS       5071100.0          0.000280  37.544963  4.738645

Price                bb_mid   bb_high       atr      macd  dollar_volume
date       ticker
2017-12-18 A            NaN       NaN -2.656965       NaN     146.904608
           AAPL         NaN       NaN -1.819493       NaN    4862.263259
           ABBV         NaN       NaN -2.172872       NaN     332.566843
           ABT          NaN       NaN -2.741538       NaN     296.664171
           ACGL         NaN       NaN -2.030007       NaN      35.109664
...                     ...       ...       ...       ...            ...
2025-12-12 XYZ     4.145287  4.212151 -0.669111 -0.379975     430.088925
           YUM     5.006037  5.047920  1.343385 -0.208794     286.183165
           ZBH     4.540548  4.596574 -0.415566 -0.266276     250.425368
           ZBRA    5.530683  5.642655 -0.375786  0.082978     145.789456
           ZTS     4.803912  4.869178 -0.022919 -1.382657     601.736745

[982534 rows x 13 columns]

In [37]:
# Build a monthly dataset so we can compare all stocks to each other each month (cross‑sectional analysis)
# Extract feature columns excluding raw price and volume data
last_cols = [c for c in df.columns.unique(0) if c not in ['dollar_volume', 'volume', 'open', 'high', 'low']]

# Resample dollar volume monthly and reshape back to multi-index format
data = (pd.concat([df.unstack('ticker')['dollar_volume'].resample('M').mean().stack('ticker').to_frame('dollar_volume'),
        df.unstack()[last_cols].resample('M').last().stack('ticker')], 
        axis = 1)).dropna()

data

                   dollar_volume       close  garman_klass_vol        rsi  \
date       ticker
2018-01-31 A          124.699618   69.282188          0.000113  66.185092
           AAPL      5107.318754   39.210739          0.000063  32.984612
           ABBV       531.232839   80.282791          0.000575  62.243678
           ABT        391.374529   54.266739          0.000082  72.163766
           ACGL        46.003407   28.824903          0.000052  50.593783
...                          ...         ...               ...        ...
2025-12-31 XYZ        527.021898   64.750000          0.000536  47.124784
           YUM        334.770393  151.059998          0.000070  55.902246
           ZBH        217.825699   91.589996          0.000351  43.820179
           ZBRA       131.000771  268.390015          0.000328  51.744682
           ZTS        626.328895  118.660004          0.000280  37.544963

                     bb_low    bb_mid   bb_high       atr      macd
date       ticker
2018-01-31 A       4.187438  4.234121  4.280804 -1.656098  0.506881
           AAPL    3.691593  3.732000  3.772407 -1.465071 -0.435790
           ABBV    4.202759  4.334643  4.466527 -0.017656  1.284161
           ABT     3.918470  3.977255  4.036040 -1.399486  0.748878
           ACGL    3.347910  3.389321  3.430732 -1.136447 -0.097422
...                     ...       ...       ...       ...       ...
2025-12-31 XYZ     4.078423  4.145287  4.212151 -0.669111 -0.379975
           YUM     4.964153  5.006037  5.047920  1.343385 -0.208794
           ZBH     4.484522  4.540548  4.596574 -0.415566 -0.266276
           ZBRA    5.418711  5.530683  5.642655 -0.375786  0.082978
           ZTS     4.738645  4.803912  4.869178 -0.022919 -1.382657

[46966 rows x 9 columns]

In [38]:
# Filter the universe by computing a 5‑year rolling dollar‑volume average, ranking stocks each month, and keeping only the top 150 most liquid names

# Compute 5-year rolling average dollar volume per stock
# Use expanding window instead of rolling
data['dollar_volume'] = (data['dollar_volume'].unstack(level=1).expanding(min_periods=12).mean().stack())

# Rank stocks by liquidity (higher dollar volume = more liquid)
data['dollar_vol_rank'] = data.groupby(level = 0)['dollar_volume'].rank(ascending=False)

# Keep only the top 150 most liquid stocks per date
data = data[data['dollar_vol_rank'] < 150].drop(['dollar_vol_rank'], axis=1)

data

                   dollar_volume       close  garman_klass_vol        rsi  \
date       ticker
2018-12-31 AAPL      6045.084072   37.496029          0.000157  37.072851
           ABBV       501.375958   68.037033          0.000167  57.957235
           ABT        356.378862   63.996525          0.000114  55.190164
           ACN        325.529903  127.567757          0.000084  36.633868
           ADBE       775.736784  226.240005          0.000161  46.330415
...                          ...         ...               ...        ...
2025-12-31 WDAY       445.679406  224.490005          0.000102  49.161349
           WFC        997.130796   92.760002          0.000092  67.810696
           WMT       1070.229696  116.699997          0.000079  67.639435
           XOM       1346.953976  118.820000          0.000081  57.247549
           XYZ       1059.701853   64.750000          0.000536  47.124784

                     bb_low    bb_mid   bb_high       atr      macd
date       ticker
2018-12-31 AAPL    3.580658  3.692733  3.804809 -0.989047 -1.075993
           ABBV    4.118541  4.189424  4.260307 -0.173547 -0.113850
           ABT     4.093232  4.150959  4.208685 -0.141786 -0.283729
           ACN     4.793551  4.926166  5.058781 -0.546122 -1.164077
           ADBE    5.329066  5.452557  5.576047 -0.277348 -0.620946
...                     ...       ...       ...       ...       ...
2025-12-31 WDAY    5.354472  5.404805  5.455139 -0.204606 -0.494058
           WFC     4.404622  4.476277  4.547933  1.984071  1.755981
           WMT     4.607937  4.703265  4.798593  2.907578  3.746652
           XOM     4.747041  4.772399  4.797758  0.702609  0.597236
           XYZ     4.078423  4.145287  4.212151 -0.669111 -0.379975

[12665 rows x 9 columns]

In [39]:
# Create monthly return features by calculating lagged pct‑changes for different time windows,
# clipping extreme outliers, and turning them into smoother per‑month returns to capture momentum.

def calculate_returns(df):
    
    outlier_cutoff = 0.005
    
    lags = [1, 2, 3, 6, 9, 12]
    
    for lag in lags:
        
        df[f'return_{lag}m'] = (df['close']
                                .pct_change(lag)
                                .pipe(lambda x: x.clip(lower=x.quantile(outlier_cutoff),
                                                       upper=x.quantile(1-outlier_cutoff)))
                                .add(1)
                                .pow(1/lag)
                                .sub(1))
    
    return df

data = data.groupby(level=1, group_keys=False).apply(calculate_returns).dropna()

data = data.drop(['dollar_volume', 'close'], axis=1)

data

                   garman_klass_vol        rsi    bb_low    bb_mid   bb_high  \
date       ticker
2019-12-31 AAPL            0.000039  77.551299  4.147183  4.216973  4.286764
           ABBV            0.000028  58.451494  4.216082  4.246336  4.276590
           ABT             0.000028  58.088713  4.337608  4.363037  4.388467
           ACN             0.000027  68.147182  5.201492  5.245035  5.288579
           ADBE            0.000018  72.249838  5.692856  5.764480  5.836104
...                             ...        ...       ...       ...       ...
2025-12-31 WDAY            0.000102  49.161349  5.354472  5.404805  5.455139
           WFC             0.000092  67.810696  4.404622  4.476277  4.547933
           WMT             0.000079  67.639435  4.607937  4.703265  4.798593
           XOM             0.000081  57.247549  4.747041  4.772399  4.797758
           XYZ             0.000536  47.124784  4.078423  4.145287  4.212151

                        atr      macd  return_1m  return_2m  return_3m  \
date       ticker
2019-12-31 AAPL   -1.203357  0.418269   0.098784   0.088117   0.095588
           ABBV   -1.194892  0.137917   0.009233   0.054993   0.058616
           ABT    -1.355874  0.322881   0.016501   0.019250   0.013902
           ACN    -1.281574  0.674170   0.046778   0.065663   0.032101
           ADBE   -1.506445  0.829873   0.065519   0.089342   0.060850
...                     ...       ...        ...        ...        ...
2025-12-31 WDAY   -0.204606 -0.494058   0.041137  -0.032691  -0.023013
           WFC     1.984071  1.755981   0.080489   0.035462   0.036168
           WMT     2.907578  3.746652   0.058166   0.075054   0.043010
           XOM     0.702609  0.597236   0.025017   0.023761   0.020591
           XYZ    -0.669111 -0.379975  -0.030689  -0.076611  -0.035963

                   return_6m  return_9m  return_12m
date       ticker
2019-12-31 AAPL     0.069174   0.050834    0.054461
           ABBV     0.038463   0.015323    0.001215
           ABT      0.006694   0.010594    0.016765
           ACN      0.022754   0.021535    0.035061
           ADBE     0.018966   0.023969    0.031909
...                      ...        ...         ...
2025-12-31 WDAY    -0.011073  -0.004377   -0.011537
           WFC      0.026613   0.030780    0.025281
           WMT      0.030670   0.032913    0.022367
           XOM      0.019403   0.002917    0.011357
           XYZ     -0.007959   0.019687   -0.022412

[10502 rows x 13 columns]

In [53]:
# Download monthly Fama–French 5-factor data, align it to our dataset,
# and merge it with each stock’s 1‑month return so we can compute rolling factor betas
factor_data = web.DataReader('F-F_Research_Data_5_Factors_2x3', 'famafrench', start = '2012')[0].drop('RF', axis = 1)
factor_data.index = factor_data.index.to_timestamp()
factor_data = factor_data.resample('M').last().div(100)
factor_data.index.name = 'date'
factor_data = factor_data.join(data['return_1m']).sort_index()
factor_data

                   Mkt-RF     SMB     HML     RMW     CMA  return_1m
date       ticker
2019-12-31 AAPL    0.0276  0.0099  0.0173  0.0005  0.0119   0.098784
           ABBV    0.0276  0.0099  0.0173  0.0005  0.0119   0.009233
           ABT     0.0276  0.0099  0.0173  0.0005  0.0119   0.016501
           ACN     0.0276  0.0099  0.0173  0.0005  0.0119   0.046778
           ADBE    0.0276  0.0099  0.0173  0.0005  0.0119   0.065519
...                   ...     ...     ...     ...     ...        ...
2025-11-30 WDAY   -0.0013  0.0147  0.0376  0.0143  0.0068  -0.101284
           WFC    -0.0013  0.0147  0.0376  0.0143  0.0068  -0.007688
           WMT    -0.0013  0.0147  0.0376  0.0143  0.0068   0.092212
           XOM    -0.0013  0.0147  0.0376  0.0143  0.0068   0.022507
           XYZ    -0.0013  0.0147  0.0376  0.0143  0.0068  -0.120358

[10361 rows x 6 columns]

In [56]:
# count how many months of data each ticker has
observations = factor_data.groupby(level=1).size()

# remove stocks with less than 10 months of data
valid_stocks = observations[observations >= 10]

# removing tickers
factor_data = factor_data[factor_data.index.get_level_values('ticker').isin(valid_stocks.index)]

factor_data

                   Mkt-RF     SMB     HML     RMW     CMA  return_1m
date       ticker
2019-12-31 AAPL    0.0276  0.0099  0.0173  0.0005  0.0119   0.098784
           ABBV    0.0276  0.0099  0.0173  0.0005  0.0119   0.009233
           ABT     0.0276  0.0099  0.0173  0.0005  0.0119   0.016501
           ACN     0.0276  0.0099  0.0173  0.0005  0.0119   0.046778
           ADBE    0.0276  0.0099  0.0173  0.0005  0.0119   0.065519
...                   ...     ...     ...     ...     ...        ...
2025-11-30 WDAY   -0.0013  0.0147  0.0376  0.0143  0.0068  -0.101284
           WFC    -0.0013  0.0147  0.0376  0.0143  0.0068  -0.007688
           WMT    -0.0013  0.0147  0.0376  0.0143  0.0068   0.092212
           XOM    -0.0013  0.0147  0.0376  0.0143  0.0068   0.022507
           XYZ    -0.0013  0.0147  0.0376  0.0143  0.0068  -0.120358

[10325 rows x 6 columns]

In [63]:
# rolling regression
# Estimate time‑varying factor betas by running a 24‑month rolling OLS for each ticker.

betas = (factor_data.groupby(level = 1, group_keys = False).apply(lambda x: RollingOLS(endog=x['return_1m'],
                                                                            exog=sm.add_constant(x.drop('return_1m', axis=1)),
                                                                            window = min(24, x.shape[0]),
                                                                            min_nobs=len(x.columns) + 1).fit(params_only = True).params.drop('const', axis=1)))
betas

                     Mkt-RF       SMB       HML       RMW       CMA
date       ticker
2019-12-31 AAPL         NaN       NaN       NaN       NaN       NaN
           ABBV         NaN       NaN       NaN       NaN       NaN
           ABT          NaN       NaN       NaN       NaN       NaN
           ACN          NaN       NaN       NaN       NaN       NaN
           ADBE         NaN       NaN       NaN       NaN       NaN
...                     ...       ...       ...       ...       ...
2025-11-30 WDAY    0.550728 -0.526554 -0.132199 -1.180634  0.583523
           WFC     1.059493 -0.210682  0.577032 -1.347265  0.076682
           WMT     1.119246 -0.334874  0.347064  0.517113 -1.003935
           XOM     0.491291 -0.560840  1.145206  0.188239 -0.027921
           XYZ     1.167420  1.500043 -1.542721 -2.358858  0.752764

[10325 rows x 5 columns]

In [68]:
factors = ["Mkt-RF", "SMB",	"HML", "RMW", "CMA"]

data = (data.join(betas.groupby('ticker').shift()))

data.loc[:, factors] = data.groupby('ticker', group_keys=False)[factors].apply(lambda x: x.fillna(x.mean()))

data = data.dropna()

data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10344 entries, (Timestamp('2019-12-31 00:00:00'), 'AAPL') to (Timestamp('2025-12-31 00:00:00'), 'XYZ')
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   garman_klass_vol  10344 non-null  float64
 1   rsi               10344 non-null  float64
 2   bb_low            10344 non-null  float64
 3   bb_mid            10344 non-null  float64
 4   bb_high           10344 non-null  float64
 5   atr               10344 non-null  float64
 6   macd              10344 non-null  float64
 7   return_1m         10344 non-null  float64
 8   return_2m         10344 non-null  float64
 9   return_3m         10344 non-null  float64
 10  return_6m         10344 non-null  float64
 11  return_9m         10344 non-null  float64
 12  return_12m        10344 non-null  float64
 13  Mkt-RF            10344 non-null  float64
 14  SMB               10344 non-null  float64
 15  HML               10344 non-null  float64
 16  RMW               10344 non-null  float64
 17  CMA               10344 non-null  float64
dtypes: float64(18)
memory usage: 1.5+ MB