In [7]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
import matplotlib.pyplot as plt
import ta
import warnings
import requests
warnings.filterwarnings("ignore")

# Scrape the S&P 500 constituents table from Wikipedia
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
response = requests.get(url, headers=headers)
sp500 = pd.read_html(response.text)[0]

# Standardize ticker symbols and extract a unique list of S&P 500 tickers
sp500['Symbol'] = sp500['Symbol'].str.replace('.', '-')
symbols_list = sp500['Symbol'].unique().tolist()

end_date = '2025-12-15'
start_date = pd.to_datetime(end_date) - pd.DateOffset(365*8)

# Download data
df = yf.download(tickers=symbols_list, start=start_date, end=end_date).stack()
df.index.names = ['date', 'ticker']
df.columns = df.columns.str.lower()

df

[*********************100%***********************]  501 of 501 completed

Price                   close        high         low        open       volume
date       ticker
2017-12-18 A        63.697105   64.497319   63.527648   63.913630    2306300.0
           AAPL     41.316132   41.498801   40.950793   40.955478  117684400.0
           ABBV     69.745354   70.391733   69.290756   69.375989    4768300.0
           ABT      49.003807   49.108070   48.152320   48.239208    6053900.0
           ACGL     28.961201   29.338389   28.923166   29.217944    1212300.0
...                       ...         ...         ...         ...          ...
2025-12-12 XYZ      64.750000   65.120003   62.799999   63.610001    6642300.0
           YUM     151.059998  151.169998  148.570007  148.899994    1894500.0
           ZBH      91.589996   93.160004   90.570000   92.599998    2734200.0
           ZBRA    268.390015  274.269989  265.970001  273.630005     543200.0
           ZTS     118.660004  121.080002  118.209999  119.190002    5071100.0

[982534 rows x 5 columns]

In [8]:
# Calculate Garman-Klass volatility using high, low, open and adjusted close prices
df['garman_klass_vol'] = ((np.log(df['high']) - np.log(df['low']))**2 / 2 - (2 * np.log(2) - 1) * (np.log(df['close']) - np.log(df['open']))**2)

# Calculate rsi on each stock
df['rsi'] = df.groupby(level=1)['close'].transform(lambda x: ta.momentum.rsi(close=x, window=20))

# Calculate Bollinger Bands for all stocks
df['bb_low'] = df.groupby(level=1)['close'].transform(lambda x: ta.volatility.BollingerBands(close=np.log1p(x), window=20).bollinger_lband())

df['bb_mid'] = df.groupby(level=1)['close'].transform(lambda x: ta.volatility.BollingerBands(close=np.log1p(x), window=20).bollinger_mavg())

df['bb_high'] = df.groupby(level=1)['close'].transform(lambda x: ta.volatility.BollingerBands(close=np.log1p(x), window=20).bollinger_hband())

# Compute a z‑score normalized 14‑day ATR(Average True Range) to capture each stock’s relative volatility profile
def compute_atr(stock_data):
    atr_indicator = ta.volatility.AverageTrueRange(
        high=stock_data['high'],
        low=stock_data['low'],
        close=stock_data['close'],
        window=14
    )
    atr = atr_indicator.average_true_range()
    return atr.sub(atr.mean()).div(atr.std())

df['atr'] = df.groupby(level=1, group_keys=False).apply(compute_atr)

# Compute a z‑score normalized MACD(Moving Average Convergence Divergence) signal to capture momentum shifts in each stock’s trend
def compute_macd(close):
    macd_indicator = ta.trend.MACD(close=close, window_slow=26, window_fast=12, window_sign=9)
    macd = macd_indicator.macd()
    return macd.sub(macd.mean()).div(macd.std())

df['macd'] = df.groupby(level=1, group_keys=False)['close'].apply(compute_macd)

# Calculate dollar volume (price × shares traded) to measure liquidity in millions of dollars
df['dollar_volume'] = (df['close']*df['volume']) / 1e6
df

Price                   close        high         low        open  \
date       ticker
2017-12-18 A        63.697105   64.497319   63.527648   63.913630
           AAPL     41.316132   41.498801   40.950793   40.955478
           ABBV     69.745354   70.391733   69.290756   69.375989
           ABT      49.003807   49.108070   48.152320   48.239208
           ACGL     28.961201   29.338389   28.923166   29.217944
...                       ...         ...         ...         ...
2025-12-12 XYZ      64.750000   65.120003   62.799999   63.610001
           YUM     151.059998  151.169998  148.570007  148.899994
           ZBH      91.589996   93.160004   90.570000   92.599998
           ZBRA    268.390015  274.269989  265.970001  273.630005
           ZTS     118.660004  121.080002  118.209999  119.190002

Price                   volume  garman_klass_vol        rsi    bb_low  \
date       ticker
2017-12-18 A         2306300.0          0.000110        NaN       NaN
           AAPL    117684400.0          0.000059        NaN       NaN
           ABBV      4768300.0          0.000113        NaN       NaN
           ABT       6053900.0          0.000098        NaN       NaN
           ACGL      1212300.0          0.000071        NaN       NaN
...                        ...               ...        ...       ...
2025-12-12 XYZ       6642300.0          0.000536  47.124784  4.078423
           YUM       1894500.0          0.000070  55.902247  4.964153
           ZBH       2734200.0          0.000351  43.820179  4.484522
           ZBRA       543200.0          0.000328  51.744682  5.418711
           ZTS       5071100.0          0.000280  37.544963  4.738645

Price                bb_mid   bb_high       atr      macd  dollar_volume
date       ticker
2017-12-18 A            NaN       NaN -2.656966       NaN     146.904634
           AAPL         NaN       NaN -1.819492       NaN    4862.264157
           ABBV         NaN       NaN -2.172871       NaN     332.566770
           ABT          NaN       NaN -2.741538       NaN     296.664148
           ACGL         NaN       NaN -2.030007       NaN      35.109664
...                     ...       ...       ...       ...            ...
2025-12-12 XYZ     4.145287  4.212151 -0.669111 -0.379975     430.088925
           YUM     5.006037  5.047920  1.343385 -0.208794     286.183165
           ZBH     4.540548  4.596574 -0.415566 -0.266276     250.425368
           ZBRA    5.530683  5.642655 -0.375786  0.082978     145.789456
           ZTS     4.803912  4.869178 -0.022919 -1.382657     601.736745

[982534 rows x 13 columns]

In [9]:
# Build a monthly dataset so we can compare all stocks to each other each month (cross‑sectional analysis)
# Extract feature columns excluding raw price and volume data
last_cols = [c for c in df.columns.unique(0) if c not in ['dollar_volume', 'volume', 'open', 'high', 'low']]

# Resample dollar volume monthly and reshape back to multi-index format
data = (pd.concat([df.unstack('ticker')['dollar_volume'].resample('M').mean().stack('ticker').to_frame('dollar_volume'),
        df.unstack()[last_cols].resample('M').last().stack('ticker')], 
        axis = 1)).dropna()

data

                   dollar_volume       close  garman_klass_vol        rsi  \
date       ticker
2018-01-31 A          124.699610   69.282188          0.000113  66.185169
           AAPL      5107.318772   39.210735          0.000063  32.984556
           ABBV       531.232825   80.282799          0.000575  62.243703
           ABT        391.374517   54.266727          0.000082  72.163599
           ACGL        46.003407   28.824903          0.000052  50.593783
...                          ...         ...               ...        ...
2025-12-31 XYZ        527.021898   64.750000          0.000536  47.124784
           YUM        334.770393  151.059998          0.000070  55.902247
           ZBH        217.825699   91.589996          0.000351  43.820179
           ZBRA       131.000771  268.390015          0.000328  51.744682
           ZTS        626.328895  118.660004          0.000280  37.544963

                     bb_low    bb_mid   bb_high       atr      macd
date       ticker
2018-01-31 A       4.187438  4.234121  4.280804 -1.656099  0.506881
           AAPL    3.691593  3.732000  3.772407 -1.465070 -0.435791
           ABBV    4.202759  4.334643  4.466527 -0.017656  1.284162
           ABT     3.918470  3.977255  4.036040 -1.399486  0.748878
           ACGL    3.347910  3.389321  3.430732 -1.136447 -0.097422
...                     ...       ...       ...       ...       ...
2025-12-31 XYZ     4.078423  4.145287  4.212151 -0.669111 -0.379975
           YUM     4.964153  5.006037  5.047920  1.343385 -0.208794
           ZBH     4.484522  4.540548  4.596574 -0.415566 -0.266276
           ZBRA    5.418711  5.530683  5.642655 -0.375786  0.082978
           ZTS     4.738645  4.803912  4.869178 -0.022919 -1.382657

[46966 rows x 9 columns]

In [10]:
# Filter the universe by computing a 5‑year rolling dollar‑volume average, ranking stocks each month, and keeping only the top 150 most liquid names

# Compute 5-year rolling average dollar volume per stock
data['dollar_volume'] = (data['dollar_volume'].unstack(level = 1).rolling(5*12).mean().stack())

# Rank stocks by liquidity (higher dollar volume = more liquid)
data['dollar_vol_rank'] = data.groupby(level = 0)['dollar_volume'].rank(ascending=False)

# Keep only the top 150 most liquid stocks per date
data = data[data['dollar_vol_rank'] < 150].drop(['dollar_volume', 'dollar_vol_rank'], axis=1)

data

                        close  garman_klass_vol        rsi    bb_low  \
date       ticker
2022-12-31 AAPL    127.998978          0.000138  39.406515  4.819161
           ABBV    144.793945          0.000171  56.394522  4.973614
           ABT     103.568306          0.000089  58.086802  4.596958
           ACN     254.872269          0.000122  44.249453  5.483890
           ADBE    336.529999          0.000069  52.172413  5.789508
...                       ...               ...        ...       ...
2025-12-31 WFC      92.760002          0.000092  67.810696  4.404622
           WMT     116.699997          0.000079  67.639435  4.607937
           XOM     118.820000          0.000081  57.247549  4.747041
           XYZ      64.750000          0.000536  47.124784  4.078423
           ZTS     118.660004          0.000280  37.544963  4.738645

                     bb_mid   bb_high       atr      macd
date       ticker
2022-12-31 AAPL    4.913838  5.008515  0.635266 -1.908169
           ABBV    4.991985  5.010356 -0.105418  0.382783
           ABT     4.632595  4.668232  0.141050  0.682825
           ACN     5.582658  5.681425  0.962295 -1.200217
           ADBE    5.817804  5.846101 -0.078577  0.153260
...                     ...       ...       ...       ...
2025-12-31 WFC     4.476277  4.547933  1.984071  1.755981
           WMT     4.703265  4.798593  2.907579  3.746653
           XOM     4.772399  4.797758  0.702609  0.597236
           XYZ     4.145287  4.212151 -0.669111 -0.379975
           ZTS     4.803912  4.869178 -0.022919 -1.382657

[5513 rows x 8 columns]

In [ ]:
# Create monthly return features by calculating lagged pct‑changes for different time windows,
# clipping extreme outliers, and turning them into smoother per‑month returns to capture momentum.

def calculate_returns(df):
    
    outlier_cutoff = 0.005
    
    lags = [1, 2, 3, 6, 9, 12]
    
    for lag in lags:
        
        df[f'return_{lag}m'] = (df['close']
                                .pct_change(lag)
                                .pipe(lambda x: x.clip(lower=x.quantile(outlier_cutoff),
                                                       upper=x.quantile(1-outlier_cutoff)))
                                .add(1)
                                .pow(1/lag)
                                .sub(1))
    
    return df

data = data.groupby(level=1, group_keys=False).apply(calculate_returns).dropna()

data

                        close  garman_klass_vol        rsi    bb_low  \
date       ticker
2023-12-31 AAPL    190.728775          0.000076  54.481871  5.242641
           ABBV    144.453903          0.000010  67.392473  4.904852
           ABT     105.909592          0.000030  68.832036  4.609143
           ACN     340.496918          0.000047  67.520514  5.775019
           ADBE    596.599976          0.000085  51.290825  6.363855
...                       ...               ...        ...       ...
2025-12-31 WFC      92.760002          0.000092  67.810696  4.404622
           WMT     116.699997          0.000079  67.639435  4.607937
           XOM     118.820000          0.000081  57.247549  4.747041
           XYZ      64.750000          0.000536  47.124784  4.078423
           ZTS     118.660004          0.000280  37.544963  4.738645

                     bb_mid   bb_high       atr      macd  return_1m  \
date       ticker
2023-12-31 AAPL    5.265166  5.287690 -0.335867  0.275169   0.013582
           ABBV    4.956684  5.008515 -0.472877  1.066533   0.088349
           ABT     4.646032  4.682920 -0.833150  1.528750   0.055422
           ACN     5.811877  5.848735 -0.065324  1.292929   0.053341
           ADBE    6.404309  6.444762  0.323715  0.014296  -0.023584
...                     ...       ...       ...       ...        ...
2025-12-31 WFC     4.476277  4.547933  1.984071  1.755981   0.080489
           WMT     4.703265  4.798593  2.907579  3.746653   0.058166
           XOM     4.772399  4.797758  0.702609  0.597236   0.025017
           XYZ     4.145287  4.212151 -0.669111 -0.379975  -0.030689
           ZTS     4.803912  4.869178 -0.022919 -1.382657  -0.074270

                   return_2m  return_3m  return_6m  return_9m  return_12m
date       ticker
2023-12-31 AAPL     0.062501   0.040352  -0.000797   0.017819    0.032943
           ABBV     0.047701   0.016414   0.027187   0.000238    0.000391
           ABT      0.078956   0.045496   0.003321   0.011029    0.001865
           ACN      0.086434   0.046887   0.022978   0.024391    0.024431
           ADBE     0.058916   0.053738   0.033706   0.049759    0.048614
...                      ...        ...        ...        ...         ...
2025-12-31 WFC      0.035462   0.036168   0.026613   0.030780    0.025281
           WMT      0.075054   0.043010   0.030670   0.032913    0.022367
           XOM      0.023761   0.020591   0.019403   0.002917    0.011357
           XYZ     -0.076611  -0.035963  -0.007959   0.019687   -0.022412
           ZTS     -0.092524  -0.066017  -0.043438  -0.034106   -0.024981

[3489 rows x 14 columns]